//! Auto-detect dependency file kinds (filename + content sniff).

use std::collections::HashMap;
use std::path::Path;
use std::sync::OnceLock;

use regex::Regex;

use super::types::FileKind;

const DETECT_READ_LIMIT: usize = 10_240;

fn file_map() -> &'static HashMap<&'static str, FileKind> {
    static MAP: OnceLock<HashMap<&'static str, FileKind>> = OnceLock::new();
    MAP.get_or_init(|| {
        HashMap::from([
            ("package.json", FileKind::PackageJson),
            ("package-lock.json", FileKind::PackageLockJson),
            ("npm-shrinkwrap.json", FileKind::PackageLockJson),
            ("yarn.lock", FileKind::YarnLock),
            ("pnpm-lock.yaml", FileKind::PnpmLock),
            ("requirements.txt", FileKind::RequirementsTxt),
            ("pipfile", FileKind::Pipfile),
            ("pipfile.lock", FileKind::PipfileLock),
            ("pyproject.toml", FileKind::PyprojectToml),
            ("composer.json", FileKind::ComposerJson),
            ("composer.lock", FileKind::ComposerLock),
            ("gemfile", FileKind::Gemfile),
            ("gemfile.lock", FileKind::GemfileLock),
            ("pom.xml", FileKind::PomXml),
            ("build.gradle", FileKind::BuildGradle),
            ("build.gradle.kts", FileKind::BuildGradle),
            ("go.mod", FileKind::GoMod),
            ("go.sum", FileKind::GoMod),
            ("cargo.toml", FileKind::CargoToml),
            ("cargo.lock", FileKind::CargoLock),
            ("packages.config", FileKind::NugetPackagesConfig),
        ])
    })
}

/// Detect file kind from path and optional content (first ~10 KiB).
pub fn detect_file_type(path: &Path, content: Option<&str>) -> FileKind {
    let basename = path
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("")
        .to_ascii_lowercase();

    if let Some(kind) = file_map().get(basename.as_str()) {
        return *kind;
    }

    if let Some(stripped) = basename.strip_prefix('.') {
        if let Some(kind) = file_map().get(stripped) {
            return *kind;
        }
        if stripped.ends_with(".csproj") {
            return FileKind::Csproj;
        }
    }

    if basename.ends_with(".csproj") {
        return FileKind::Csproj;
    }

    let Some(content) = content else {
        return FileKind::Unknown;
    };
    detect_from_content(content)
}

/// Content-only sniff used for `--url` bodies and unknown filenames.
pub fn detect_from_content(content: &str) -> FileKind {
    let sample = if content.len() > DETECT_READ_LIMIT {
        &content[..DETECT_READ_LIMIT]
    } else {
        content
    };
    let trimmed = sample.trim_start();
    if trimmed.is_empty() {
        return FileKind::Unknown;
    }

    if trimmed.starts_with('{') {
        return detect_json(sample, content);
    }

    detect_text(sample)
}

fn detect_json(sample: &str, full: &str) -> FileKind {
    if sample.contains("\"lockfileVersion\"") {
        return FileKind::PackageLockJson;
    }
    if sample.contains("\"resolved\"") && sample.contains("\"integrity\"") {
        return FileKind::PackageLockJson;
    }
    if sample.contains("\"_meta\"") && sample.contains("\"pipfile-spec\"") {
        return FileKind::PipfileLock;
    }

    let data: serde_json::Value = match serde_json::from_str(full) {
        Ok(v) => v,
        Err(_) => return FileKind::Unknown,
    };
    let Some(obj) = data.as_object() else {
        return FileKind::Unknown;
    };

    if obj.get("requires").and_then(|v| v.as_bool()) == Some(true)
        && obj.contains_key("dependencies")
    {
        return FileKind::PackageLockJson;
    }

    if let Some(deps) = obj.get("dependencies").and_then(|v| v.as_object()) {
        if let Some((_, first)) = deps.iter().next() {
            if first.is_object() {
                return FileKind::PackageLockJson;
            }
            if first.is_string() {
                return FileKind::PackageJson;
            }
        }
    }

    if obj.contains_key("require") || obj.contains_key("require-dev") {
        return FileKind::ComposerJson;
    }

    if let Some(pkgs) = obj.get("packages").and_then(|v| v.as_array()) {
        if let Some(first) = pkgs.first().and_then(|v| v.as_object()) {
            if first.contains_key("name") {
                return FileKind::ComposerLock;
            }
        }
    }

    if obj.contains_key("default") && obj.contains_key("develop") {
        return FileKind::PipfileLock;
    }

    if obj.contains_key("devDependencies")
        || obj.contains_key("peerDependencies")
        || obj.contains_key("name")
    {
        return FileKind::PackageJson;
    }

    FileKind::Unknown
}

fn detect_text(sample: &str) -> FileKind {
    let lower = sample.to_ascii_lowercase();
    if sample.contains("# THIS IS AN AUTOGENERATED FILE") && lower.contains("yarn") {
        return FileKind::YarnLock;
    }

    static YARN_KEY: OnceLock<Regex> = OnceLock::new();
    let yarn_key = YARN_KEY
        .get_or_init(|| Regex::new(r#"(?m)^"?@?[\w/.-]+@[^:]+:\s*$"#).expect("yarn key regex"));
    if yarn_key.is_match(sample) && sample.contains("version ") {
        return FileKind::YarnLock;
    }

    static GO_MOD: OnceLock<Regex> = OnceLock::new();
    let go_mod =
        GO_MOD.get_or_init(|| Regex::new(r"(?m)^\s*module\s+\S+").expect("go module regex"));
    static GO_VER: OnceLock<Regex> = OnceLock::new();
    let go_ver = GO_VER.get_or_init(|| Regex::new(r"(?m)^\s*go\s+\d").expect("go ver regex"));
    if go_mod.is_match(sample) && go_ver.is_match(sample) {
        return FileKind::GoMod;
    }

    if sample.contains("<project")
        && (sample.contains("<dependencies>") || sample.contains("<dependency>"))
    {
        return FileKind::PomXml;
    }

    static PKG_REF: OnceLock<Regex> = OnceLock::new();
    let pkg_ref =
        PKG_REF.get_or_init(|| Regex::new(r"(?m)^\s*<PackageReference\s").expect("csproj regex"));
    if pkg_ref.is_match(sample) {
        return FileKind::Csproj;
    }

    static GRADLE: OnceLock<Regex> = OnceLock::new();
    let gradle = GRADLE.get_or_init(|| {
        Regex::new(r#"(implementation|compile|api|testImplementation)\s*[\('"']"#)
            .expect("gradle regex")
    });
    if gradle.is_match(sample) {
        return FileKind::BuildGradle;
    }

    static PIPFILE: OnceLock<Regex> = OnceLock::new();
    let pipfile = PIPFILE.get_or_init(|| Regex::new(r"(?m)^\[packages\]").expect("pipfile regex"));
    if pipfile.is_match(sample) {
        return FileKind::Pipfile;
    }

    static CARGO_TOML: OnceLock<Regex> = OnceLock::new();
    let cargo_pkg =
        CARGO_TOML.get_or_init(|| Regex::new(r"(?m)^\[package\]").expect("cargo package"));
    static CARGO_DEPS: OnceLock<Regex> = OnceLock::new();
    let cargo_deps =
        CARGO_DEPS.get_or_init(|| Regex::new(r"(?m)^\[dependencies\]").expect("cargo deps"));
    if cargo_pkg.is_match(sample) && cargo_deps.is_match(sample) {
        return FileKind::CargoToml;
    }

    static CARGO_LOCK: OnceLock<Regex> = OnceLock::new();
    let cargo_lock =
        CARGO_LOCK.get_or_init(|| Regex::new(r"(?m)^\[\[package\]\]").expect("cargo lock"));
    if cargo_lock.is_match(sample) && sample.contains("name = \"") {
        return FileKind::CargoLock;
    }

    static GEMFILE: OnceLock<Regex> = OnceLock::new();
    let gemfile = GEMFILE.get_or_init(|| Regex::new(r#"(?m)^gem\s+['"]"#).expect("gemfile regex"));
    if gemfile.is_match(sample) {
        return FileKind::Gemfile;
    }

    static GEM_SPECS: OnceLock<Regex> = OnceLock::new();
    let gem_specs =
        GEM_SPECS.get_or_init(|| Regex::new(r"(?m)^\s{4}\S+\s+\(").expect("gemfile.lock specs"));
    if sample.contains("specs:") && gem_specs.is_match(sample) {
        return FileKind::GemfileLock;
    }

    static REQ: OnceLock<Regex> = OnceLock::new();
    let req = REQ.get_or_init(|| {
        Regex::new(r"(?m)^[a-zA-Z0-9_][\w.-]*\s*[=<>!~]=").expect("requirements regex")
    });
    if req.is_match(sample) {
        return FileKind::RequirementsTxt;
    }

    if sample.contains("lockfileVersion") {
        return FileKind::PnpmLock;
    }

    FileKind::Unknown
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn detects_package_json_by_name() {
        assert_eq!(
            detect_file_type(Path::new("package.json"), None),
            FileKind::PackageJson
        );
    }

    #[test]
    fn detects_csproj_by_suffix() {
        assert_eq!(
            detect_file_type(Path::new("App.csproj"), None),
            FileKind::Csproj
        );
    }

    #[test]
    fn detects_go_mod_by_content() {
        let c = "module example.com/foo\n\ngo 1.22\n";
        assert_eq!(detect_from_content(c), FileKind::GoMod);
    }
}
